server:
  port: 9001
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/weather
#    username: root
#    password: mindfire
#  jpa:
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#    show-sql: true
  data:
    mongodb:
      database: local
      uri: mongodb://localhost:27017/local
  application:
    name: city-service
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
eureka:
  instance:
    hostname: localhost
