server:
  port: 8762

eureka:
  instance:
    hostname: localhost
      
spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
      - id: city-service
        uri: lb://city-service
        predicates:
        - Path=/city/**
      - id: weather-service
        uri: lb://weather-service
        predicates:
        - Path=/weather/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedMethods: "*"
            allowedHeaders: "*"    

    
  